runtime: nodejs10
service: default
handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    # catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

env_variables:
  NODE_ENV: 'production'
  API_URL: 'https://api-dot-mybudgetpipauls.ew.r.appspot.com/api/v1/'