# Docker compose version
version: "2"
services:

# Client docker
  client:
    container_name: loop-client
# server sources are locatted into ./client, we need to set the root ./client for the Docker builder
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
# Open port 80
    ports:
      - "80:80"
    environment:
      NODE_ENV: development
# Mount root to taken into account code updates
# ignore /usr/server/node_modules
    volumes:
      - .:/usr/client
      - /usr/client/node_modules
# Waiting for server
# Run nodemon using "npm run watch"
    command: ["npm", "run", "watch"]
